language: node_js
node_js:
  - "20.11.1"

cache:
  directories:
    - node_modules

before_install:
  - npm install -g yarn

install:
  - yarn install

script:
  - yarn run build

notifications:
  email:
    recipients:
      - elaine610.lau@gmail.com
    on_success: always
    on_failure: always
